#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/System/Volumes/Data/Development/FlutterSetup/flutter"
export "FLUTTER_APPLICATION_PATH=/System/Volumes/Data/Development/Projects/AdiBook"
export "FLUTTER_TARGET=/System/Volumes/Data/Development/Projects/AdiBook/lib/main.dart"
export "FLUTTER_BUILD_DIR=build"
export "SYMROOT=${SOURCE_ROOT}/../build/ios"
export "OTHER_LDFLAGS=$(inherited) -framework Flutter"
export "FLUTTER_FRAMEWORK_DIR=/System/Volumes/Data/Development/FlutterSetup/flutter/bin/cache/artifacts/engine/ios"
export "FLUTTER_BUILD_NAME=1.0.0"
export "FLUTTER_BUILD_NUMBER=1"
export "DART_OBFUSCATION=false"
export "TRACK_WIDGET_CREATION=true"
export "TREE_SHAKE_ICONS=false"
export "PACKAGE_CONFIG=.packages"
